# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProtobufTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProtobufTest
pod 'SwiftProtobuf'
end

target 'ProtobufTestTests' do
pod 'SwiftProtobuf'   
end